name: apt setup

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name:
          df
        run:
          df -h

      - name:
          sudo apt list installed
        run:
          sudo apt list --installed

      - name:
          apt delete
        run:
          sudo apt -y remove --auto-remove --purge aspnetcore* docker* dotnet* firefox* golang* google* mono* mysql* nginx* php* ruby*

      - name:
          apt install 1 of 2
        run:
          sudo apt -y install asciidoc bash binutils bzip2 flex git g++ gcc time util-linux gawk gzip help2man intltool libelf-dev zlib1g-dev make libncurses-dev libssl-dev patch perl-modules libthread-queue-any-perl python2-dev python3-dev unzip wget gettext xsltproc zlib1g-dev libboost-dev libxml-parser-perl libusb-dev bin86 bcc sharutils gcc-multilib openjdk-7-jdk-headless b43-fwcutter zip

      - name:
          apt install 2 of 2
        run:
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          
      - name:
          apt clean 1 of 3
        run:
          sudo apt -y autoremove --purge
          
      - name:
          apt clean 2 of 3
        run:
          sudo apt -y autoclean
          
      - name:
          apt clean 3 of 3
        run:
          sudo apt -y clean

      - name:
          delete
        run: |
          sudo rm -rf /usr/local/lib/android/sdk
          sudo rm -rf /usr/local/share/chromedriver-linux64
          sudo rm -rf /usr/local/share/edge_driver
          sudo rm -rf /usr/local/share/gecko_driver
          sudo rm -rf /usr/share/java/selenium-server.jar
          sudo rm -rf /usr/share/java
          sudo rm -rf /usr/share/miniconda
          sudo rm -rf /usr/local/share/vcpkg

      - name:
          df
        run:
          df -h
