# This is a basic workflow to help you get started with Actions

name: apt setup

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name:
          df
        run:
          df -h

      - name:
          sudo apt list installed
        run:
          sudo apt list --installed

      - name:
          apt delete
        run:
          sudo apt -y purge --auto-remove aspnetcore* docker* dotnet* firefox* golang* google* mono* mysql* nginx* php* python* ruby*

      - name:
          apt install 1 of 2
        run:
          sudo apt -y install asciidoc bash binutils bzip2 flex git g++ gcc time util-linux gawk gzip help2man intltool libelf-dev zlib1g-dev make libncurses-dev libssl-dev patch perl-modules libthread-queue-any-perl python2-dev python3-dev unzip wget gettext xsltproc zlib1g-dev

      - name:
          apt install 2 of 2
        run:
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          
      - name:
          df
        run:
          df -h
  