name:
  Build base

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest

    steps:
      - name: 
          Update and install packages
        run: |
          sudo apt -y remove --auto-remove --purge firefox snapd
          sudo apt -y update
          sudo apt -y full-upgrade
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo apt -y autoremove --purge
          sudo apt -y autoclean
          sudo apt -y clean

      - name:
          Checkout this repository
        uses:
          actions/checkout@v4
        with:
          fetch-depth:
            1

      - name:
          Checkout openwrt/openwrt repository
        uses:
          actions/checkout@v4
        with: 
          repository:
            openwrt/openwrt
          path:
            openwrt
          fetch-depth:
            1

      - name:
          Checkout openwrt/packages repository
        uses:
          actions/checkout@v4
        with: 
          repository:
            openwrt/packages
          path:
            openwrt/feeds/packages
          fetch-depth:
            1

      - name:
          Checkout openwrt/luci repository
        uses:
          actions/checkout@v4
        with: 
          repository:
            openwrt/luci
          path:
            openwrt/feeds/luci
          fetch-depth:
            1

      - name:
          Checkout openwrt/routing repository
        uses:
          actions/checkout@v4
        with: 
          repository:
            openwrt/routing
          path:
            openwrt/feeds/routing
          fetch-depth:
            1

      - name:
          Checkout openwrt/telephony repository
        uses:
          actions/checkout@v4
        with: 
          repository:
            openwrt/telephony
          path:
            openwrt/feeds/telephony
          fetch-depth:
            1

      - name:
          Applying customisation
        working-directory:
          openwrt
        run:
          patch -Np1 < ../feeds.github.patch

      - name:
          Update feeds step 1 of 2
        working-directory:
          openwrt
        run:
          ./scripts/feeds update -a

      - name:
          Update feeds step 2 of 2
        working-directory:
          openwrt
        run:
          ./scripts/feeds update -a

      - name:
          Install feeds step 1 of 2
        working-directory:
          openwrt
        run:
          ./scripts/feeds install -a

      - name:
          Install feeds step 2 of 2
        working-directory:
          openwrt
        run:
          ./scripts/feeds install -a

      - name:
          Import target configuration
        working-directory:
          openwrt
        run:
          cp ../target_config/ath79.generic.config .config

      - name:
          Apply target configuration
        working-directory:
          openwrt
        run:
          make defconfig

      - name:
          Pre-download sources
        working-directory:
          openwrt
        run:
          time make -j$(nproc) download

      - name:
          Build tools
        working-directory:
          openwrt
        run:
          time make -j$(nproc) tools

      - name:
          Build toolchain
        working-directory:
          openwrt
        run:
          time make -j$(nproc) toolchain
