name: Build firmware for ELECOM WAB-I1750-PS

on:
  schedule:
    - cron: '23 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt -y purge --auto-remove --purge snapd* firefox*
          sudo apt -y update
          sudo apt -y full-upgrade --auto-remove --purge
          sudo apt -y install --auto-remove --purge build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo apt -y autopurge
          sudo apt -y autoclean
          sudo apt -y clean

      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: config

      - name: Clone OpenWrt repository
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt.git

      - name: Setup to build
        working-directory: openwrt
        run: |
          patch -Np1 < ../config/feeds.main.patch
          git clone --depth=1 https://github.com/openwrt/packages.git feeds/packages 
          git clone --depth=1 https://github.com/openwrt/luci.git feeds/luci  
          git clone --depth=1 https://github.com/openwrt/routing.git feeds/routing
          git clone --depth=1 https://github.com/openwrt/telephony.git feeds/telephony
          ./scripts/feeds update -a
          ./scripts/feeds update -a
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          cp ../config/.config .
          make defconfig

      - name: Pre-download sources
        working-directory: openwrt
        run: time make download

      - name: Do the build
        working-directory: openwrt
        run: time make -j$(nproc) V=c

      - name: Make release
        working-directory: openwrt
        run: |
          set -xe
          shopt -s nullglob
          RELDATE="$(date +'%Y-%m-%d %H:%M')"
          NAME="Auto-Build $RELDATE"
          TAGNAME="autobuild-$(date +'%Y-%m-%d-%H-%M')"
          gh release create "$TAGNAME" --target "main" --title "$NAME" bin/targets/ath79/generic/*.{bin,buildinfo,manifest,json} bin/targets/ath79/generic/sha256sums
          echo "tag_name=${TAGNAME}" >> $GITHUB_OUTPUT
          echo "rel_date=${RELDATE}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}
