name: Build OpenWrt target build base

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      subtarget:
        required: true
        type: string      

  workflow_dispatch: 
    inputs:
      target:
        required: true
        type: string
      subtarget:
        required: true
        type: string      

jobs:

  build_base:
    name: Build target build base (${{ inputs.target }}, ${{ inputs.subtarget }})
    runs-on: ubuntu-22.04

    env:
      CCACHE_DEPEND: true
      CCACHE_SLOPPINESS: file_macro,locale,time_macros

    steps:
      - name: Run apt tasks
        run: |
          sudo apt -qq -y remove --auto-remove --purge aspnet* docker* dotnet* firefox* google* mono* snapd*
          sudo rm -rf /etc/docker /etc/mono /usr/lib/mono /usr/libexec/docker /usr/share/dotnet
          sudo apt -qq -y update
          sudo apt -qq -y full-upgrade --auto-remove --purge
          sudo apt -qq -y install --auto-remove --purge b43-fwcutter bash bcc bin86 binutils bzip2 ccache flex g++ gawk gcc gcc-multilib gettext git gzip help2man intltool libboost-dev libelf-dev libncurses-dev libssl-dev libthread-queue-any-perl libusb-dev libxml-parser-perl make openjdk-8-jdk-headless patch perl-modules python3-dev sharutils time unzip util-linux wget xsltproc zip zlib1g-dev bison build-essential clang file g++-multilib python3-distutils rsync
          sudo apt -qq -y clean

      - name: df check
        run: df -h

      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone openwrt/openwrt repository
        run: git clone --depth=1 https://github.com/openwrt/openwrt.git

      - name: Clone openwrt/packages repository
        working-directory: openwrt
        run: git clone --depth=1 https://github.com/openwrt/packages.git feeds/packages

      - name: Clone openwrt/luci repository
        working-directory: openwrt
        run: git clone --depth=1 https://github.com/openwrt/luci.git feeds/luci  

      - name: Clone openwrt/routing repository
        working-directory: openwrt
        run: git clone --depth=1 https://github.com/openwrt/routing.git feeds/routing

      - name: Clone openwrt/telephony repository
        working-directory: openwrt
        run: git clone --depth=1 https://github.com/openwrt/telephony.git feeds/telephony

      - name: Ccache cache
        uses: actions/cache@v4
        with:
          key: ${{ inputs.target }}.${{ inputs.subtarget }}.buildcache-${{ github.run_id }}.${{ github.run_attempt }}
          restore-keys: ${{ inputs.target }}.${{ inputs.subtarget }}.buildcache-
          path: |
            openwrt/.ccache

      - name: Apply customisation
        working-directory: openwrt
        run: patch -Np1 < ../feeds.github.patch

      - name: Update feeds
        working-directory: openwrt
        run: ./scripts/feeds update -a

      - name: Install feeds
        working-directory: openwrt
        run: ./scripts/feeds install -a

      - name: Import build configuration (target specification)
        working-directory: openwrt
        run: cat ../target_config/${{ inputs.target }}.${{ inputs.subtarget }}.config > .config

      - name: Apply build configuration
        working-directory: openwrt
        run: make defconfig

      - name: Download sources
        working-directory: openwrt
        run: make -j$(nproc) download

      - name: Build tools, toolchain
        working-directory: openwrt
        run: make -j$(nproc) tools/compile toolchain/compile

      - name: Cleanup
        working-directory: openwrt
        run: make clean

      - name: Show ccache statistics
        working-directory: openwrt
        run: CCACHE_DIR=$(pwd)/.ccache ccache -s

      - name: Create target build base cache
        uses: actions/cache/save@v4
        with:
          key: ${{ inputs.target }}.${{ inputs.subtarget }}.buildbase-${{ github.run_id }}.${{ github.run_attempt }}
          path: openwrt
