name: Build OpenWrt firmwares (predefined automatic)

permissions:
  contents: write

on:
# schedule:
#   - cron: '0 15 * * *'
#
  workflow_dispatch:
    

jobs:

  build_base:
    name: Build target build base
    uses: ./.github/workflows/build.target-base.yml
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
    strategy:
      matrix:
        target: [ath79]
        subtarget: [generic]

  build_firmware-elecom_wab:
    name: Build and release firmware (for ELECOM WAB series)
    needs: build_base
    uses: ./.github/workflows/build.target-profile.yml
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      profile: ${{ matrix.profile }}
      dorelease: true
    strategy:
      matrix:
        target: [ath79]
        subtarget: [generic]
        profile: [elecom_wab-i1750-ps,elecom_wab-s1167-ps,elecom_wab-s600-ps]
