# This is a basic workflow to help you get started with Actions

name: Build firmware

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Clone OpenWrt repository
        with:
          repository: openwrt/openwrt
          path: openwrt-main

      - name: Clone OpenWrt repository
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
