name:
  Build firmware for ELECOM WAB-I1750-PS

on:
  schedule:
    - cron: '0 15 * * *'

  workflow_dispatch:

jobs:

  call-workflow:
    uses: ./.github/workflows/build.yml
    with:
      target: ath79
      subtarget: generic
      profile: base

    steps:
      - name:
          Download artifacts
        uses:
          actions/download-artifact@v4

      - name:
          Make release
        run: |
          ls -laFR
          set -xe
          shopt -s nullglob
          RELDATE="$(date +'%Y-%m-%d %H:%M')"
          NAME="Auto-Build $RELDATE"
          TAGNAME="autobuild-$(date +'%Y-%m-%d-%H-%M')"
          gh release create "$TAGNAME" --repo ${{ github.repository }} --target "main" --title "$NAME" artifact/targets/ath79/generic/*.{bin,buildinfo,json,manifest} artifact/targets/ath79/generic/sha256sums
          echo "tag_name=${TAGNAME}" >> $GITHUB_OUTPUT
          echo "rel_date=${RELDATE}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN:
            ${{ github.token }}
