# This is a basic workflow to help you get started with Actions

name: Build firmware

# Controls when the workflow will run
on:
  schedule:
    - cron: '23 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout configurations
        uses: actions/checkout@v4
        with:
          path: config

      - name: Clone OpenWrt repository
        run: |
          pwd
          git clone --depth=2 https://github.com/openwrt/openwrt.git

      - name: Change directory
        run: |
          pwd
          cd openwrt
          pwd

      - name: Configure OpenWrt feeds repository
        run: |
          pwd
          patch -Np1 < ../config/feeds.main.patch
          pwd

      - name: Clone OpenWrt feeds repository
        run: |
          pwd
          git clone --depth=2 https://github.com/openwrt/packages.git feeds/packages 
          git clone --depth=2 https://github.com/openwrt/luci.git feeds/luci  
          git clone --depth=2 https://github.com/openwrt/routing.git feeds/routing
          git clone --depth=2 https://github.com/openwrt/telephony.git feeds/telephony
          pwd

      - name: Installing feeds packages
        run: |
          pwd
          ./scripts/feeds update -a
          ./scripts/feeds update -a
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          pwd
      
      - name: Including build configuration
        run: |
          pwd
          cp ../config/.config .
          pwd

      - name: Run the builder
        run: |
          pwd
          time make -j3
