name:
  Build firmware for ELECOM WAB series

on:
  schedule:
    - cron: '0 15 * * *'

  workflow_dispatch:

    
jobs:

  build-base:
    uses: ./.github/workflows/build.yml
    with:
      target: ath79
      subtarget: generic
      profile: base

  build-profile:
    needs: build-base
    strategy:
      matrix:
        profile: [elecom_wab-i1750-ps]
    uses: ./.github/workflows/build.yml
    with:
      target: ath79
      subtarget: generic
      profile: ${{ matrix.profile }}

#  steps:
#    - name:
#      Download artifacts
#        uses:
#          actions/download-artifact@v4
#
#      - name:
#          Make release
#        run: |
#          ls -laFR
#          set -xe
#          shopt -s nullglob
#          RELDATE="$(date +'%Y-%m-%d %H:%M')"
#          NAME="Auto-Build $RELDATE"
#          TAGNAME="autobuild-$(date +'%Y-%m-%d-%H-%M')"
#          gh release create "$TAGNAME" --repo ${{ github.repository }} --target "main" --title "$NAME" artifact/targets/ath79/generic/*.{bin,buildinfo,json,manifest} artifact/targets/ath79/generic/sha256sums
#          echo "tag_name=${TAGNAME}" >> $GITHUB_OUTPUT
#          echo "rel_date=${RELDATE}" >> $GITHUB_OUTPUT
#        env:
#          GITHUB_TOKEN:
#            ${{ github.token }}
