# This is a basic workflow to help you get started with Actions

name: Build firmware for ELECOM WAB-I1750-PS

# Controls when the workflow will run
on:
  schedule:
    - cron: '23 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repository to configurations
        uses: actions/checkout@v4
        with:
          path: config

      - name: Clone OpenWrt repository and setup to build
        run: |
          git clone --depth=2 https://github.com/openwrt/openwrt.git
          cd openwrt
          patch -Np1 < ../config/feeds.main.patch
          git clone --depth=2 https://github.com/openwrt/packages.git feeds/packages 
          git clone --depth=2 https://github.com/openwrt/luci.git feeds/luci  
          git clone --depth=2 https://github.com/openwrt/routing.git feeds/routing
          git clone --depth=2 https://github.com/openwrt/telephony.git feeds/telephony
          ./scripts/feeds update -a
          ./scripts/feeds update -a
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          cp ../config/.config .

      - name: Do the build
        run: |
          cd openwrt
          time make -j3
