name: Release OpenWrt device firmware

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      subtarget:
        required: true
        type: string
      profile:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      target:
        required: true
        type: string
      subtarget:
        required: true
        type: string
      profile:
        required: true
        type: string

jobs:

  packing:
    name: Packing firmware to release (${{ inputs.target }} > ${{ inputs.subtarget }} > ${{ inputs.profile }})
    runs-on: ubuntu-22.04

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts.${{ inputs.target }}.${{ inputs.subtarget }}.${{ inputs.profile }}
        path: artifacts

    - name: Make release
      run: |
        ls -laFR
        set -xe
        shopt -s nullglob
        RELDATE="$(date +'%Y-%m-%d %H:%M')"
        NAME="Firmware for ${{ inputs.target }}.${{ inputs.subtarget }}.${{ inputs.profile }}, Auto-Build"
        TAGNAME="${{ inputs.target }}.${{ inputs.subtarget }}.${{ inputs.profile }}__autobuild-$(date +'%Y-%m-%d-%H-%M')"
        gh release create "$TAGNAME" --repo ${{ github.repository }} --title "$NAME" artifacts/*
        echo "tag_name=${TAGNAME}" >> $GITHUB_OUTPUT
        echo "rel_date=${RELDATE}" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN:
          ${{ github.token }}
