name:
  Build base for ath79.generic

on:
  schedule:
    - cron: '0 14 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest

    steps:
      - name: Cache build base
        uses:
          actions/cache@v3
        with:
          key:
            build.ath79.${{ github.run_id }}.${{ github.run_attempt }}
          restore-keys: |
            build.ath79.
          path: |
            openwrt

      - name:
          dir
        run:
          ls -laFR
